const SERVICES = [
  {
    id: '1',
    img: 'yape.png',
    option: 'Yape Fake',
    message: [
      '🚀 **YAPE FAKE - 2026**',
      '',
      'Activa tu licencia de forma segura aquí.',
      '💰 **Precio:** S/ 40',
      '',
      '✅ **Pago único**',
      '✅ **Acceso permanente**',
      '✅ **Actualizaciones automáticas**',
      '',
      'Si deseas adquirirlo, escribe: `/pagar`',
    ],
  },
  {
    id: '2',
    img: 'xpress.png',
    option: 'Bot Resellers',
    message: [
      '🚀 **BOT YAPE XPRESS**',
      '',
      'Gestiona y activa licencias de Yape Fake.',
      'Compra créditos y utilízalos para activar cuentas.',
      '',
      '✅ **Sistema de créditos**',
      '✅ **Activación inmediata**',
      '✅ **Control total de tus consumos e historial**',
      '',
      'Ideal para resellers que buscan ganar comisiones y manejar sus propias activaciones.',
      '',
      '🤖 Bot: @yapexpress_bot',
      '🎬 Escribe `/tutorial` en el bot y mira cómo funciona',
    ],
  },
  {
    id: '3',
    img: 'vip.png',
    option: 'Contenido VIP',
    message: [
      '🔞 **GRUPO VIP CONTENIDO PREMIUM**',
      '',
      'Accede al grupo privado con contenido exclusivo.',
      'Encontrarás material de influencers, tiktokers peruanas, castings y contenido casero.',
      '',
      '💰 **Precio:** S/ 50',
      '',
      '✅ Pago único',
      '✅ Acceso permanente',
      '✅ Fotos y videos exclusivos',
      '✅ Contenido nuevo constantemente',
      '✅ Descarga todo el material',
      '',
      'Si deseas adquirirlo ,escribe: `/pagar`',
    ],
  },
  {
    id: '4',
    img: 'followers.png',
    option: 'Seguidores',
    message: [
      '🚀 **SEGUIDORES PARA REDES SOCIALES**',
      '',
      '💯 Impulsa tu perfil y aumenta tu alcance.',
      '',
      '✅ **Entrega inmediata**',
      '✅ **Tiempo de servicio:** 5 a 30 minutos',
      '✅ **Sin límite de cantidad**, tú decides',
      '',
      'Si deseas solicitar un pedido, escribe: `/pagar`',
      ,
    ],
  },
  {
    id: '5',
    img: 'doxing.png',
    option: 'Doxeos',
    message: [
      '🔎 **SERVICIOS DE DOXEOS**',
      '',
      'Realiza búsquedas mediante:',
      '',
      '✅ **DNI o nombres completos**',
      '✅ **Número de celular**',
      '✅ **Placa vehicular**',
      '',
      'Si deseas solicitar una consulta, escribe: `/pagar`',
    ],
  },
];

const serviceRows = SERVICES.map((service) => `**${service.id}** = ${service.option}`);
const SERVICES_MESSAGE = ['📋 **Servicios disponibles**', '', ...serviceRows, '', '✍️ Escribe un **número**'].join(
  '\n',
);

module.exports = {
  SERVICES,
  SERVICES_MESSAGE,
};
